#!/bin/bash

# Stop on the first error
set -e

# Attempt to change directory to the directory containing the script
script_dir=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
cd "$script_dir" || { 
    echo "Error: Failed to change to the script's directory. Please check the path."
    exit 1
}

# Check if activate.sh exists
if [ ! -f "./activate.sh" ]; then
    echo "Error: 'activate.sh' not found in the current directory. Have you installed the project? Try running './install'."
    exit 1
fi

# Activate the environment
. ./activate.sh

# Run the Python development script
python run_dev.py || {
    echo "Error: Python script 'run_dev.py' failed to run. Have you installed the dependencies? Try running './install'."
    exit 1
}
