#! /bin/bash

# Function to clean up background processes
cleanup() {
    echo "Cleaning up background processes..."
    kill $(jobs -p) 2>/dev/null
}

# Trap EXIT and SIGINT (Ctrl-C) to call the cleanup function
trap cleanup EXIT SIGINT

# Attempt to change directory to the directory containing the script
script_dir=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
cd "$script_dir" || { 
    echo "Error: Failed to change to the script's directory. Please check the path."
    exit 1
}

cd www

# Run npm build and check if it fails
if ! npm run build; then
    echo "Error: npm run build failed. Have you installed the dependencies? Try running './install'."
    exit 1
fi

cd ..

# Start background processes
uvicorn --host 0.0.0.0 --port 80 --workers 8 --forwarded-allow-ips=* feedthewatchdogs.app:app &
python -m feedthewatchdogs.background_tasks &

# Wait for all background processes to finish
wait
